# Generated by Django 4.2.8 on 2024-09-12 08:35

import apps.user.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="User Name"
                    ),
                ),
                (
                    "email",
                    apps.user.models.LowercaseEmailField(
                        max_length=255, unique=True, verbose_name="Email"
                    ),
                ),
                ("password", models.CharField(max_length=200, verbose_name="Password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last login"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(default=False, verbose_name="Superuser"),
                ),
                ("is_staff", models.BooleanField(default=False, verbose_name="Staff")),
                (
                    "fcm_token",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="FCM Token"
                    ),
                ),
                (
                    "created_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_updated_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_last_updated_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_name",
                    models.CharField(
                        default="empty",
                        max_length=100,
                        unique=True,
                        verbose_name="Page Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Descriptions",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "creation_date",
                    models.DateField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "last_updated_date",
                    models.DateField(auto_now=True, verbose_name="Last Updated At"),
                ),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_name",
                    models.CharField(max_length=100, verbose_name="Role Name"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Descriptions",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "creation_date",
                    models.DateField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "last_updated_date",
                    models.DateField(auto_now=True, verbose_name="Last Updated At"),
                ),
                (
                    "is_system_role",
                    models.BooleanField(default=False, verbose_name="Is System Role"),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="RolePageAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view", models.BooleanField(default=True, verbose_name="View")),
                ("add", models.BooleanField(default=False, verbose_name="Add")),
                ("edit", models.BooleanField(default=False, verbose_name="Edit")),
                (
                    "created_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_page_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.page",
                        verbose_name="Page",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.role",
                        verbose_name="Role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Page Assignment",
                "verbose_name_plural": "Role Page Assignments",
            },
        ),
        migrations.AddField(
            model_name="role",
            name="page",
            field=models.ManyToManyField(
                through="user.RolePageAssignment",
                to="user.page",
                verbose_name="Role Page",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_role",
            field=models.ManyToManyField(
                blank=True,
                related_name="assign_role",
                to="user.role",
                verbose_name="User Roles",
            ),
        ),
    ]
