# Generated by Django 4.2.8 on 2024-09-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False, verbose_name="Superuser"),
        ),
    ]
