# Generated by Django 4.2.8 on 2024-09-14 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_user_is_superuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_superuser",
        ),
    ]
