# Generated by Django 4.2.8 on 2024-09-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_user_is_staff_user_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolepageassignment",
            name="delete",
            field=models.BooleanField(default=False, verbose_name="Delete"),
        ),
    ]
